#!/bin/bash


main() {
  if [[ ! "$1" ]]; then
    helpAndExit
  elif [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]]; then
    helpAndExit

  elif [[ "$1" == "total" ]] || [[ "$1" == "all" ]]; then
    if [[ -n "$2" ]]; then
      showCombinedFileSizesInDir "$2"
    else
      showCombinedFileSizesInDir "."
    fi

  elif [[ $1 =~ ^[0-9]+$ ]]; then
    if [[ -n "$2" ]]; then
      showLargestNFilesInDir "$1" "$2"
    else
      showLargestNFilesInDir "$1" "."
    fi

  else
    helpAndExit
  fi
}

helpAndExit() {
  echo "Usage: $0 <all|#>"
  exit 1
}

showCombinedFileSizesInDir() {
  du -sh "$1"
}

showLargestNFilesInDir() {
  FILE_QUANTITY="$1"
  find "$2" -type f -exec du -h {} + 2>/dev/null | sort -rh | head -n "$FILE_QUANTITY" | GREP_COLORS="mt=1;32" grep --color="always" "^.*K\s" | tac
  echo " "
  find "$2" -type f -exec du -h {} + 2>/dev/null | sort -rh | head -n "$FILE_QUANTITY" | GREP_COLORS="mt=1;33" grep --color="always" "^.*M\s" | tac
  echo " "
  find "$2" -type f -exec du -h {} + 2>/dev/null | sort -rh | head -n "$FILE_QUANTITY" | GREP_COLORS="mt=1;31" grep --color="always" "^.*G\s" | tac
}

main "$@"

